#!/usr/bin/php


<?php

echo "\nInstaller running\n";

system("git clone https://github.com/pjreddie/darknet");

//~ system("mv -v darknet/* .");
system("cd darknet && make");

system("wget https://pjreddie.com/media/files/tiny-yolo-voc.weights");


