#!/usr/bin/php

<?php

#> imagemagick

$GLOBALS['opt'] = [];

echo "\033[31;1;4;5;7m##### Left #####\e[0m\n"; 


if (isset($argv[1])) {

  if ($argv[1] === "url"){
   
     echo "mode: ".$argv[1]."\n";
   
     $url = readline("jpg url: ");
   
     system("wget -A jpg,jpeg -O out.jpg $url");
   
     webcam();
  
    }
  
  if ($argv[1] === "screen"){
   
      echo "mode: ".$argv[1]."\n";
    
      $GLOBALS['opt'] = "screen";

    }
  
  }

if (!isset($argv[1])) {
	
	  webcam();
	
  }

function webcam() {
	
  system("ffmpeg -nostats -loglevel 0 -f video4linux2 -y -i /dev/video0 -ss 0:0:2 -frames 1 out.jpg > /dev/null");

  }

$robot = popen("./darknet detector test cfg/voc.data cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights out_M-0.jpg -thres 0 2 > scanpop_L", "w");

$robot = file_get_contents("scanpop_L");

if (!isset($robot)) {

	if (stripos($robot[0], "Predicted") !== false) {
		
	    echo "\n#### Idle ####";
	
	} 
}
			 
$robot = explode("\n",$robot);

$robot[0] = "";

$scene = count($robot) - 2;

$person = 0;$person++;

if ($scene >= 1) {
	
	$job = implode("\n", $robot);
	
	$job = explode(": \n", $job);
	
	$job = implode("", $robot);
	
	$job = explode(": ", $job);

	echo "\e[7m".$scene." ".$job[0]."\e[0m\n";
	
	$obj = $scene." ".$job[0];
	
	if ($scene === 1){
	  $obj = $scene." ".$job[0];
	};	
	if ($scene != 1){
	  $obj = $job[0];
	};
	if ($scene > 1){
	  $obj = $scene." ".$job[0];
	};
	
	
	$okay = $job[0];

	@system("ffplay -nodisp -autoexit ./voices/$okay.mp3 &");

	@system("ffplay -nodisp -autoexit ./voices/gauche.mp3 &");

	
	if ($job[0] === "person") {
		
		$job[0];
		
		$person++;
		
		echo "\n".$person;
		
		
		}
	
	}
	
$robot = implode("\n", $robot);	

print_r($opt);


if (!isset($opt[0])){

system("./scan");

 exit();

} else {
	
	popen("./scan_L $opt", "w");

	exit();
       
	}
