#!/usr/bin/php

<?php

#> imagemagick

echo "Usage: ./scan [[url|screen|webcam|cam] [en|fr]\n";
echo "------------------------------------------\n";
echo "\033[33;1;4;5;7m##### Main #####\e[0m\n"; 

$GLOBALS['opt'] = [];

if (isset($argv[1])) {

  if ($argv[1] === "url"){
   
     echo "mode: ".$argv[1]."\n";
   
     $url = readline("jpg url: ");
   
     system("wget -A jpg,jpeg -O out.jpg $url");
   
     webcam();
  
    }
  
  if ($argv[1] === "screen"){
   
      echo "mode: ".$argv[1]."\n";
  
      system("ffmpeg -nostats -loglevel 0 -y -f x11grab -video_size 1280x900 -i \$DISPLAY -vframes 1 out.jpg > /dev/null");
 
      //~ system("convert -scale 60% +repage out.jpg out.jpg");
      
      system("convert -crop 44%x100% +repage out.jpg out_M.jpg");
    
      $GLOBALS['opt'] = "screen";

    }
    
  if ($argv[1] === "cam"){
   
      echo "mode: ".$argv[1]."\n";
  
      system("ffmpeg -y -i rtsp://192.168.42.1/live -f image2 out.jpg > /dev/null");

      system("convert -crop 33%x100% +repage out.jpg out_M.jpg");

      $GLOBALS['opt'] = "cam";

    }
  
  }

if (!isset($argv[1])) {
	
	  webcam();
	
  }

function webcam() {
	
  system("ffmpeg -nostats -loglevel 0 -f video4linux2 -y -i /dev/video0 -ss 0:0:2 -frames 1 out.jpg > /dev/null");

  }

$robot = popen("./darknet detector test cfg/voc.data cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights out.jpg -thres 0 2 > scanpop", "w");

$robot = file_get_contents("scanpop");

if (!isset($robot)) {

	if (stripos($robot[0], "Predicted") !== false) {
		
	    echo "\n#### Idle ####";
	
	} 
}
	
print_r($robot);
		 
$robot = explode("\n",$robot);

$robot[0] = "";

$scene = count($robot) - 2;

echo $scene." ";

$person = 0;$person++;

if ($scene >= 1) {
	
	$job = implode("\n", $robot);
	
	$job = explode(": \n", $job);
	
	$job = implode("", $robot);
	
	$job = explode(": ", $job);

	echo "\e[7m".$scene." ".$job[0]."\e[0m\n";
	
	if ($scene === 1){
	  $obj = $scene." ".$job[0];
	};	
	if ($scene != 1){
	  $obj = $job[0];
	};
	if ($scene > 1){
	  $obj = $scene." ".$job[0];
	};
	
	$okay = $job[0];
	
	$okay_a = $job[1];

	@system("ffplay -loglevel panic -nodisp -autoexit ./voices/$okay.mp3 &");

	system("espeak -p 15 -v fr-fr '$obj'");
	//~ system("gtts-cli '$obj' --lang fr | mpg123 - &");

	@system("img2txt out.jpg &");
	
	//~ if ($job[0] === "person") {
	if ($job[0] === "pieton") {
		
		$job[0];
		
		$person++;
		
		echo "\n".$person;
		
		
		}
	
	}
	
$robot = implode("\n", $robot);	

print_r($opt);


if (!isset($opt[0])){

 system("./scan");
 
 exit();

} else {
	
	system("./scan $opt");
        
	exit();
	
   }

